# Generated by Django 3.1.7 on 2021-06-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(help_text='Audio file', upload_to='audios'),
        ),
    ]
